import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar"; 
import { WebSocketProvider } from "../context/WebSocketProvider"; // Asegúrate de ajustar la ruta
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SODA",
  description: "Generated by Soda",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme') || 'default';
                document.documentElement.setAttribute('data-theme', theme);
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-base-content`}>
        <Navbar />
        <WebSocketProvider>
          <main>{children}</main>
        </WebSocketProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}